# Generated by Django 3.1.7 on 2021-06-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Computer'), ('L', 'Laptop'), ('S', 'Smartphone')], max_length=2),
        ),
    ]
